# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-10 07:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0002_auto_20160909_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='city',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='contact',
            field=models.TextField(blank=True, null=True, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='country',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='engine_number',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Engine Number'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='frame_number',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Frame Number'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='make',
            field=models.CharField(max_length=256, verbose_name='Make'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='model',
            field=models.CharField(max_length=256, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='state',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800)], verbose_name='Year'),
        ),
    ]
